apiVersion: v1
kind: Namespace # <1>
metadata:
  name: ${K8S_NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount # <2>
metadata:
  namespace: ${K8S_NAMESPACE}
  name: gdk-service-acct
---
kind: Role # <3>
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ${K8S_NAMESPACE}
  name: gdk_service_role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps", "secrets", "pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # <4>
metadata:
  namespace: ${K8S_NAMESPACE}
  name: gdk_service_role_bind
subjects:
  - kind: ServiceAccount
    name: gdk-service-acct
roleRef:
  kind: Role
  name: gdk_service_role
  apiGroup: rbac.authorization.k8s.io